// Original AI cover artwork; source prompts are recorded in docs/COVER-ART.md.
export const coverArt: Record<string, string> = {
  "dau-pha-thuong-khung": "/covers/dau-pha-thuong-khung.webp",
  "vu-dong-can-khon": "/covers/vu-dong-can-khon.webp",
  "dai-chua-te": "/covers/dai-chua-te.webp",
  "nguyen-ton": "/covers/nguyen-ton.webp",
  "than-quoc-chi-thuong": "/covers/than-quoc-chi-thuong.webp",
  "ta-se-mai-tang-chung-than": "/covers/ta-se-mai-tang-chung-than.webp",
  "trach-thien-ky": "/covers/trach-thien-ky.webp",
  "tru-tien-tan-tu": "/covers/tru-tien-tan-tu.webp",
  "linh-canh-hanh-gia": "/covers/linh-canh-hanh-gia.webp",
  "tien-nghich": "/covers/tien-nghich.webp",
  "nguoc-ve-thoi-minh": "/covers/nguoc-ve-thoi-minh.webp",
  "muc-than-ky": "/covers/muc-than-ky.webp",
  "trach-nhat-phi-thang": "/covers/trach-nhat-phi-thang.webp",
  "thon-phe-tinh-khong": "/covers/thon-phe-tinh-khong.webp",
  "pham-nhan-tu-tien": "/covers/pham-nhan-tu-tien.webp",
  "nhat-niem-vinh-hang": "/covers/nhat-niem-vinh-hang.webp",
  "cau-ma": "/covers/cau-ma.webp",
  "dai-phung-da-canh-nhan": "/covers/dai-phung-da-canh-nhan.webp",
  "khanh-du-nien": "/covers/khanh-du-nien.webp",
  "tuong-da": "/covers/tuong-da.webp",
  "dau-la-dai-luc": "/covers/dau-la-dai-luc.webp",
  "tuyet-the-duong-mon": "/covers/tuyet-the-duong-mon.webp",
  "ban-long": "/covers/ban-long.webp",
  "quy-bi-chi-chu": "/covers/quy-bi-chi-chu.webp",
  "suu-than-ky": "/covers/suu-than-ky.webp",
  "van-dao-truong-sinh": "/covers/van-dao-truong-sinh.webp",
  "kiem-khai-thien-mon": "/covers/kiem-khai-thien-mon.webp",
  "nguyet-ha-truong-an": "/covers/nguyet-ha-truong-an.webp",
  "tinh-ha-ky": "/covers/tinh-ha-ky.webp",
  "son-ha-co-nhan": "/covers/son-ha-co-nhan.webp",
  "nhat-niem-pham-tran": "/covers/nhat-niem-pham-tran.webp",
  "nguoi-giu-mua-ha": "/covers/nguoi-giu-mua-ha.webp",
  "thanh-pho-khong-ngu": "/covers/thanh-pho-khong-ngu.webp"
};
