ALTER TABLE "Bookmark" ADD COLUMN "shelf" TEXT NOT NULL DEFAULT 'READING', ADD COLUMN "followed" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "ReadingProgress" ADD COLUMN "position" DOUBLE PRECISION NOT NULL DEFAULT 0, ADD COLUMN "finished" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Comment" ADD COLUMN "hidden" BOOLEAN NOT NULL DEFAULT false, ADD COLUMN "parentId" TEXT;
ALTER TABLE "Comment" ADD CONSTRAINT "Comment_parentId_fkey" FOREIGN KEY ("parentId") REFERENCES "Comment"("id") ON DELETE SET NULL ON UPDATE CASCADE;
CREATE INDEX "Comment_storyId_createdAt_idx" ON "Comment"("storyId","createdAt");
CREATE TABLE "Notification" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "title" TEXT NOT NULL, "href" TEXT NOT NULL, "eventKey" TEXT NOT NULL, "readAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Notification_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Notification_eventKey_key" ON "Notification"("eventKey");
CREATE INDEX "Notification_userId_createdAt_idx" ON "Notification"("userId","createdAt");
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE TABLE "ChapterDraft" ("revision" INTEGER NOT NULL DEFAULT 0,"id" TEXT NOT NULL,"storyId" TEXT NOT NULL,"title" TEXT NOT NULL DEFAULT '',"content" TEXT NOT NULL DEFAULT '',"isFree" BOOLEAN NOT NULL DEFAULT true,"price" INTEGER NOT NULL DEFAULT 0,"status" TEXT NOT NULL DEFAULT 'DRAFT',"scheduledAt" TIMESTAMP(3),"chapterId" TEXT,"error" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "ChapterDraft_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "ChapterDraft_chapterId_key" ON "ChapterDraft"("chapterId");
CREATE INDEX "ChapterDraft_status_scheduledAt_idx" ON "ChapterDraft"("status","scheduledAt");
ALTER TABLE "ChapterDraft" ADD CONSTRAINT "ChapterDraft_storyId_fkey" FOREIGN KEY ("storyId") REFERENCES "Story"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "Story_status_updatedAt_idx" ON "Story"("status","updatedAt");
CREATE INDEX "Bookmark_storyId_followed_idx" ON "Bookmark"("storyId","followed");
CREATE INDEX "ReadingProgress_storyId_idx" ON "ReadingProgress"("storyId");
CREATE INDEX "Rating_storyId_idx" ON "Rating"("storyId");
CREATE INDEX "ChapterPurchase_chapterId_createdAt_idx" ON "ChapterPurchase"("chapterId","createdAt");
CREATE INDEX "ChapterDraft_storyId_updatedAt_idx" ON "ChapterDraft"("storyId","updatedAt");
ALTER TABLE "ReadingProgress" ADD CONSTRAINT "ReadingProgress_position_check" CHECK ("position" >= 0 AND "position" <= 1);
ALTER TABLE "Bookmark" ADD CONSTRAINT "Bookmark_shelf_check" CHECK ("shelf" IN ('READING','FAVORITE','FINISHED'));
ALTER TABLE "ChapterDraft" ADD CONSTRAINT "ChapterDraft_status_check" CHECK ("status" IN ('DRAFT','SCHEDULED','PUBLISHED','FAILED'));
ALTER TABLE "ChapterDraft" ADD CONSTRAINT "ChapterDraft_price_check" CHECK ("price" >= 0 AND "price" <= 100);
ALTER TABLE "ChapterDraft" ADD CONSTRAINT "ChapterDraft_schedule_check" CHECK ("status" != 'SCHEDULED' OR "scheduledAt" IS NOT NULL);
